project:
  type: website
  preview:
    host: 192.168.10.102
    port: 4415
    browser: false

website:
  title: "website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



