project:
  type: website
  preview:
    host: 192.168.10.104
    port: 4415
    browser: false


website:
  title: "IS415-GAA - swoh"
  site-url: https://is415-swoh.netlify.app
  

  navbar:
    left:
      - text: "Hands-On Exercises"
        menu:
          - text: "Hands-On Exercise 1"
            href: ./hands_on_exercises/exercise_1/exercise.qmd
          - text: "Hands-On Exercise 2"
            href: ./hands_on_exercises/exercise_2/exercise.qmd
    
      - text: "In-Class Exercises"
        menu:
          - text: "In-Class Exercise 1"
            href: ./in_class_exercises/exercise_1/exercise.qmd

      - text: "Take-Home Exercises"

    right:
      - text: "Home"
        href: index.qmd

      - text: "About"
        href: ./about/about.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    number-sections: true



